---
# tasks file for zookeeper
# code: language=ansible
- name: Install required packages
  become: true
  ansible.builtin.package:
    name: "{{ zookeeper_install_packages }}"
    state: present
  tags:
    - zookeeper_install_packages

- name: Install python packages
  become: true
  ansible.builtin.pip:
    name: "{{ zookeeper_python_packages }}"
  tags:
    - zookeeper_python_packages

- name: Ensure user zookeeper exists
  become: true
  ansible.builtin.user:
    name: "{{ zookeeper_user }}"
    shell: /bin/bash

- name: Ensure ZooKeeper directories exist
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    state: directory
    recurse: false
    mode: "0755"
  loop:
    - "{{ zookeeper_base_dir }}"
    - "{{ zookeeper_conf_dir }}"
    - "{{ zookeeper_conf_dir }}/conf"
    - "{{ zookeeper_log_dir }}"
    - "{{ zookeeper_working_dir }}"

- name: Get archive from S3
  amazon.aws.s3_object:
    bucket: "{{ zookeeper_binary_bucket }}"
    object: "{{ zookeeper_binary_prefix }}{{ zookeeper_binary_name }}"
    dest: "/tmp/{{ zookeeper_binary_name }}"
    mode: get

- name: Rertieve and unarchive ZooKeeper
  become: true
  ansible.builtin.unarchive:
    src: "/tmp/{{ zookeeper_binary_name }}"
    dest: "{{ zookeeper_base_dir }}"
    mode: "0755"
    extra_opts: ['--strip-components=1', '--show-stored-names']
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    remote_src: true

- name: Remove base conf to avoid confusion
  become: true
  ansible.builtin.file:
    path: "{{ zookeeper_base_dir }}/conf"
    state: absent

- name: Copy out ZooKeeper cfg file
  become: true
  ansible.builtin.template:
    src: "zoo.cfg.j2"
    dest: "{{ zookeeper_config_file }}"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    mode: '0644'

- name: Copy files
  become: true
  ansible.builtin.copy:
    src: "logback.xml"
    dest: "{{ zookeeper_conf_dir }}/conf"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    mode: "0644"

- name: Copy ZooKeeper myid file to data directory
  become: true
  ansible.builtin.template:
    src: "myid.j2"
    dest: "{{ zookeeper_working_dir }}/myid"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    mode: "0644"

- name: Copy out ZooKeeper service file
  become: true
  ansible.builtin.template:
    src: "zookeeper.service.j2"
    dest: /usr/lib/systemd/system/zookeeper.service
    owner: root
    group: root
    mode: "0644"

- name: Reload systemd since we just added a new ZooKeeper service
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Enable and start the ZooKeeper service
  become: true
  ansible.builtin.systemd_service:
    state: started
    name: zookeeper
    enabled: true
