---
# code: language=ansible
# tasks file for ignite
- name: Install required packages
  become: true
  ansible.builtin.package:
    name: "{{ install_packages }}"
    state: present
  tags:
    - install_packages

- name: Ensure user ignite exists
  become: true
  ansible.builtin.user:
    name: "{{ ignite_user }}"
    shell: /bin/bash

- name: Ensure ignite directories exist
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ ignite_user }}"
    group: "{{ ignite_group }}"
    state: directory
    recurse: false
    mode: "0755"
  loop:
    - "{{ ignite_snapshots_dir }}"
    - "{{ ignite_work_dir }}"
    - "{{ ignite_log_dir }}"
    - "{{ ignite_conf_dir }}"
    - "{{ ignite_data_dir }}"
    - "{{ ignite_pid_dir }}"

- name: Rertieve and unarchive ignite
  become: true
  ansible.builtin.unarchive:
    src: "{{ ignite_binary_url }}"
    dest: "/tmp"
    mode: "0755"
    owner: "{{ ignite_user }}"
    group: "{{ ignite_group }}"
    remote_src: true
  register: unzip

- name: Rename ignite base directory
  become: true
  ansible.builtin.copy:
    src: "{{ uzip.path }}"
    dest: "{{ ignite_base_dir }}"
    mode: "0755"
    owner: "{{ ignite_user }}"
    group: "{{ ignite_group }}"

- name: Copy content of directory 'files'
  become: true
  ansible.builtin.copy:
    src: "{{ ignite_optional_libs_dir }}/{{ item }}"
    dest: "{{ ignite_libs_dir }}"
    mode: "0755"
    owner: "{{ ignite_user }}"
    group: "{{ ignite_group }}"
  loop: "{{ plugins }}"

- name: Copy ignite config file to conf directory
  become: true
  ansible.builtin.template:
    src: "config.xml.j2"
    dest: "{{ ignite_config_file }}"
    owner: "{{ ignite_user }}"
    group: "{{ ignite_group }}"
    mode: "0644"

- name: Copy ignite log file config to conf directory
  become: true
  ansible.builtin.template:
    src: "log4j2.xml.j2"
    dest: "{{ ignite_log_file }}"
    owner: "{{ ignite_user }}"
    group: "{{ ignite_group }}"
    mode: "0644"

- name: Copy ignite service definition file to system directory
  become: true
  ansible.builtin.template:
    src: "ignite.service.j2"
    dest: "{{ ignite_service_file }}"
    owner: "{{ ignite_user }}"
    group: "{{ ignite_group }}"
    mode: "0644"

- name: Reload systemd since we just added a new ignite service
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Enable and start the ignite service
  become: true
  ansible.builtin.systemd_service:
    state: started
    name: ignite
    enabled: true
