---
# vars file for ignite
# code: language=ansible

# ignite binary url
ignite_binary_name: "apache-ignite-2.13.0-bin.zip"
ignite_binary_prefix: "bins/"
ignite_binary_bucket: "tf-backend-craig"
ignite_snapshot_bucket: "craig-snapshot-bucket"

# aws s3-mount
ignite_s3_mount: "https://s3.amazonaws.com/mountpoint-s3-release/latest/x86_64/mount-s3.rpm"
ignite_efs_id: "fs-0568d3403bce7eb7c"

# Directories
ignite_base_dir: "/opt/ignite"
ignite_snapshots_dir: "/opt/snapshots"
ignite_work_dir: "{{ ignite_base_dir }}/work"
ignite_log_dir: "/var/log/ignite"
ignite_conf_dir: "/etc/ignite/conf"
ignite_data_dir: "/var/lib/ignite"
ignite_pid_dir: "/var/run/ignite"
ignite_optional_libs_dir: "{{ ignite_base_dir }}/libs/optional"
ignite_libs_dir: "{{ ignite_base_dir }}/libs"

# plugins
ignite_plugins:
  - ignite-log4j2
  - ignite-zookeeper

# files
ignite_config_file: "{{ ignite_conf_dir }}/config.xml"
ignite_pid_file: "{{ ignite_pid_dir }}/ignite.pid"
ignite_log_config_file: "{{ ignite_conf_dir }}/log4j2-config.xml"
ignite_service_file: "/usr/lib/systemd/system/ignite.service"

# kafa user/group
ignite_user: "ignite"
ignite_group: "ignite"

# required packages
ignite_install_packages:
  - java-11-amazon-corretto
  - python3-pip
  - amazon-efs-utils

ignite_python_packages:
  - botocore
  - boto3
