---
# tasks file for kafka
- name: install required packages
  become: true
  package:
    name: "{{ install_packages }}"
    state: present
  tags:
    - install_packages

- name: ensure user kafka exists
  become: true
  ansible.builtin.user:
    name: "{{ kafka_user }}"
    shell: /bin/bash
    
- name: ensure kafka directories exist
  become: true
  file:
    path: "{{ item }}"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    state: directory
    recurse: no
    mode: 0755
  loop:
    - "{{ kafka_base_dir }}"
    - "{{ kafka_conf_dir }}"
    - "{{ kafka_conf_dir }}/conf"
    - "{{ kafka_log_dir }}"
    - "{{ kafka_data_dir }}"

- name: rertieve and unarchive kafka
  become: true
  ansible.builtin.unarchive:
    src: "{{ kafka_binary_url }}"
    dest: "{{ kafka_base_dir }}"
    mode: '0755'
    extra_opts: ['--strip-components=1', '--show-stored-names']
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    remote_src: yes

- name: copy kafka server.properties file to conf directory
  become: true
  ansible.builtin.template:
    src: "server.properties.j2"
    dest: "{{ kafka_conf_dir }}/conf/server.properties"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: '0644'

- name: copy kafka log4j.properties file to conf directory
  become: true
  ansible.builtin.template:
    src: "log4j.properties.j2"
    dest: "{{ kafka_log4j_prop_file }}"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: '0644'

- name: copy kafka service defenition file to system directory
  become: true
  ansible.builtin.template:
    src: "kafka.service.j2"
    dest: "{{ kafka_service_file }}"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: '0644'

- name: reload systemd since we just added a new kafka service
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: enable and start the kafka service
  become: true
  ansible.builtin.systemd_service:
    state: started
    name: kafka
    enabled: true