---
# vars file for zookeeper

# Zookeeper Binary URL
zookeeper_binary_prefix: "bins/apache-zookeeper-3.8.4-bin.tar.gz"
binary_bucket: "tf-backend-craig"

# Directories
zookeeper_base_dir: "/opt/zookeeper"
zookeeper_log_dir: "/var/log/zookeeper"
zookeeper_conf_dir: "/etc/zookeeper"
zookeeper_working_dir: "/var/lib/zookeeper"
zookeeper_pid_dir: "/var/run/zookeeper"

# Files
zookeeper_var_file: "{{ zookeeper_conf_dir }}/conf/zookeeper-env-vars"
zookeeper_config_file: "{{ zookeeper_conf_dir }}/conf/zoo.cfg"

# ZooKeeper User/Group
zookeeper_user: "zookeeper"
zookeeper_group: "zookeeper"

# ZooKeeper conf settings
zookeeper_client_port: 2181

# Required packages 
install_packages:
  - java-11-amazon-corretto
  - python3-pip

python_packages:
  - botocore
  - boto3