---
# vars file for kafka

# kafka binary url
kafka_binary_url: "https://downloads.apache.org/kafka/3.7.0/kafka_2.12-3.7.0.tgz"

# Directories
kafka_base_dir: "/opt/kafka"
kafka_log_dir: "/var/log/kafka"
kafka_conf_dir: "/etc/kafka"
kafka_data_dir: "/var/lib/kafka"
kafka_pid_dir: "/var/run/kafka"

# files
kafka_config_file: "{{ kafka_conf_dir }}/conf/server.properties"
kafka_pid_file: "{{ kafka_pid_dir }}/kafka.pid"
kafka_log4j_prop_file: "{{ kafka_conf_dir }}/conf/log4j.properties"
kafka_service_file: "/usr/lib/systemd/system/kafka.service"

# kafa user/group
kafka_user: "kafka"
kafka_group: "kafka"

# required packages 
install_packages:
  - java-11-amazon-corretto